source :gemcutter
gem "sinatra"
gem "sinatra-reloader"
#gem "reloader", :git => "git://github.com/rkh/sinatra-reloader.git"
gem "haml"
gem "will_paginate", :git => "git://github.com/mislav/will_paginate.git", :branch => "rails3"
gem "activesupport", "2.3.8"
gem "mongo"
gem "bson_ext"
gem "ruby-graphviz"
gem "sinatra-cache"
